const videoData = [
    {
        tags: "seal sea mammal",
        poster: "https://picsum.photos/200/",
        cardTitle: "Seal",
        cardText: "Pinnipeds, commonly known as seals, are a widely distributed and diverse clade of carnivorous, fin-footed, semiaquatic, mostly marine mammals",
        modalid: "seal",
        modalTitle: "Seal",
        linkButton: "#",
    },
    {
        tags: "turtle land sea reptile",
        poster: "https://picsum.photos/200/",
        cardTitle: "Turtle",
        cardText: "Turtles are an order of reptiles known as Testudines, characterized by a shell developed mainly from their ribs",
        modalid: "turtle",
        modalTitle: "Turtle",
        linkButton: "#",
    },
    {
        tags: "penguin land sea bird",
        poster: "https://picsum.photos/200/",
        cardTitle: "Penguin",
        cardText: "Penguins (order Sphenisciformes) are a group of aquatic flightless birds. They live almost exclusively in the southern hemisphere",
        modalid: "penguin",
        modalTitle: "Penguin",
        linkButton: "#",
    },
    {
        tags: "alpaca land mammal",
        poster: "https://picsum.photos/200/",
        cardTitle: "Alpaca",
        cardText: "The alpaca (Lama pacos) is a species of South American camelid mammal. It is similar to, and often confused with, the llama. However, alpacas are often noticeably smaller than llamas",
        modalid: "alpaca",
        modalTitle: "Alpaca",
        linkButton: "#",
    },
    {
        tags: "monkey land mammal",
        poster: "https://picsum.photos/200/",
        cardTitle: "Monkey",
        cardText: "Monkey is a common name that may refer to most mammals of the infraorder Simiiformes, also known as the simians. Traditionally, all animals in the group now known as simians are counted as monkeys except the apes",
        modalid: "monkey",
        modalTitle: "Monkey",
        linkButton: "#",
    },
    {
        tags: "dog mammal",
        poster: "https://picsum.photos/200/",
        cardTitle: "Dog",
        cardText: "The dog or domestic dog (Canis familiaris) is a domesticated descendant of the wolf, characterized by an upturning tail. The dog derived from an ancient, extinct wolf, and the modern grey wolf is the dog's nearest living relative",
        modalid: "dog",
        modalTitle: "Dog",
        linkButton: "#",
    }
    ];