const projectData = [
    {
        tags: "medselect unbranded postcard hcpyes pdfno dseno vaeno emailcustomno",
        topImg: "../images/90147bmsAfibPostcardMedselect/afib-thumb.PNG",
        cardTitle: "90147 Pfizer BMS AFib Postcard",
        cardText: "Medselect &#9679; Unbranded &#9679; Postcard &#9679; HCP toggle",
        modalid: "afibCard",
        modalTitle: "AFib Postcard",
        slideTwo: "../images/90147bmsAfibPostcardMedselect/afibTwo.PNG",
        slideThree: "../images/90147bmsAfibPostcardMedselect/afibThree.PNG",
        slideFour: "../images/90147bmsAfibPostcardMedselect/afibFour.PNG",
        linkButton: "",
        trainingButton: "n/a"
    },
    {
        tags: "patientprofiler branded pdfno hcpno dseno vaeyes emailcustomyes",
        topImg: "../images/90138cyclosetPatientProfiler/cycloset-thumb.PNG",
        cardTitle: "90138 Bausch-Salix Cycloset Patient Profiler",
        cardText: "Patient profiler &#9679; Branded &#9679; Approved Email",
        modalid: "cyclosetCard",
        modalTitle: "Cycloset Patient Profiler",
        slideTwo: "../images/90138cyclosetPatientProfiler/cyclosetTwo.PNG",
        slideThree: "../images/90138cyclosetPatientProfiler/cyclosetThree.PNG",
        slideFour: "../images/90138cyclosetPatientProfiler/cyclosetFour.PNG",
        linkButton: "",
        trainingButton: ""
    },
    {
        tags: "kolselect branded pdfno hcpno dseno vaeyes",
        topImg: "../images/90116tremfyaDermKolselect/tremfya-thumb.PNG",
        cardTitle: "90116 Janssen Tremfya Derm KOL Select",
        cardText: "KOL Select &#9679; Branded &#9679; Approved Email",
        modalid: "tremfyaCard",
        modalTitle: "Tremfya Derm KOL",
        slideTwo: "../images/90116tremfyaDermKolselect/tremfyaTwo.PNG",
        slideThree: "../images/90116tremfyaDermKolselect/tremfya-thumb.PNG",
        slideFour: "../images/90116tremfyaDermKolselect/tremfyaTwo.PNG",
        linkButton: "",
        trainingButton: "n/a"
    },
    {
        tags: "medselect branded brochure pdfyes hcpyes dseno vaeno emailcustomno",
        topImg: "../images/90156janssenSpravatoMedselect/spravato-thumb.PNG",
        cardTitle: "90156 Janssen Spravato MED Select",
        cardText: "MED Select &#9679; Branded &#9679; Brochure &#9679; PDF Delivery &#9679; HCP toggle",
        modalid: "spravatoCard",
        modalTitle: "Spravato MED Select",
        slideTwo: "../images/90156janssenSpravatoMedselect/spravatoTwo.PNG",
        slideThree: "../images/90156janssenSpravatoMedselect/spravatoThree.PNG",
        slideFour: "../images/90156janssenSpravatoMedselect/spravatoFour.PNG",
        linkButton: "",
        trainingButton: ""
    },
    {
        tags: "medselect unbranded tearpad wallchart pdfno hcpyes dseno vaeno emailcustomno",
        topImg: "../images/17014PfizerEnbrelMEDSelect/pfizerEnbrel-thumb.PNG",
        cardTitle: "17014 Pfizer Enbrel MED Select",
        cardText: "MED Select &#9679; Unbranded &#9679; Wallchart &#9679; Tearpad &#9679; HCP toggle",
        modalid: "enbrelcard",
        modalTitle: "Pfizer Enbrel MED Select",
        slideTwo: "../images/17014PfizerEnbrelMEDSelect/pfizerEnbrel-two.PNG",
        slideThree: "../images/17014PfizerEnbrelMEDSelect/pfizerEnbrel-three.PNG",
        slideFour: "../images/17014PfizerEnbrelMEDSelect/pfizerEnbrel-four.PNG",
        linkButton: "",
        trainingButton: ""
    },
    {
        tags: "medselect branded tearpad pdfno hcpno dseno vaeno emailcustomno",
        topImg: "../images/90097endoNascobalMedselect/nascobal-thumb.PNG",
        cardTitle: "90097 Endo Nascobal MED Select",
        cardText: "MED Select &#9679; Branded &#9679; Tearpad",
        modalid: "nascobalCard",
        modalTitle: "Endo Nascobal MED Select",
        slideTwo: "../images/90097endoNascobalMedselect/nascobalTwo.PNG",
        slideThree: "../images/90097endoNascobalMedselect/nascobalThree.PNG",
        slideFour: "../images/90097endoNascobalMedselect/nascobalFour.PNG",
        linkButton: "",
        trainingButton: "n/a"
    },
    {
        tags: "medselect unbranded tearpad wallchart pdfno hcpyes dseno vaeno emailcustomno",
        topImg: "../images/90146merckKeytrudaMedSelect/keytruda-thumb.PNG",
        cardTitle: "90146 Merck Keytruda MED Select",
        cardText: "MED Select &#9679; Unbranded &#9679; Wallchart &#9679; Tearpad &#9679; HCP toggle",
        modalid: "keytrudaCard",
        modalTitle: "Merck Keytruda MED Select",
        slideTwo: "../images/90146merckKeytrudaMedSelect/keytrudaTwo.PNG",
        slideThree: "../images/90146merckKeytrudaMedSelect/keytrudaThree.PNG",
        slideFour: "../images/90146merckKeytrudaMedSelect/keytrudaFour.PNG",
        linkButton: "",
        trainingButton: ""
    }
    ];
